#!/usr/bin/env python3
"""
MCP Gateway CLI

Usage:
  mcp-gateway init     — create .env in current folder
  mcp-gateway start    — start the gateway on :8000
  mcp-gateway list     — list registered servers
  mcp-gateway add      — add a server to registry
  mcp-gateway remove   — remove a server from registry
"""
import argparse
import os
import sys
import secrets
import shutil
from pathlib import Path


def cmd_init(args):
    env_path = Path(".env")
    if env_path.exists():
        print("✓ .env already exists")
        return

    # Look for .env.example in package or current dir
    example = Path(__file__).parent / ".env.example"
    if not example.exists():
        example = Path(".env.example")

    if example.exists():
        shutil.copy(example, env_path)
    else:
        key = secrets.token_hex(24)
        env_path.write_text(
            f"# MCP Gateway — generated by mcp-gateway init\n"
            f"MCP_API_KEYS={key}\n"
            f"HOST=0.0.0.0\n"
            f"PORT=8000\n"
        )

    # Replace placeholder key
    content = env_path.read_text()
    if "change-me-before-use" in content:
        content = content.replace("change-me-before-use", secrets.token_hex(24))
        env_path.write_text(content)

    print("✓ .env created")
    print("✓ API key generated")
    print("\nNext: run  mcp-gateway start")


def cmd_start(args):
    from dotenv import load_dotenv
    load_dotenv()

    host = os.getenv("HOST", "0.0.0.0")
    port = int(os.getenv("PORT", args.port or 8000))
    reload = args.reload

    print(f"\n  MCP Gateway v1.0.0")
    print(f"  http://localhost:{port}\n")

    import uvicorn
    uvicorn.run(
        "gateway.main:app",
        host=host,
        port=port,
        reload=reload,
        log_level="info",
    )


def cmd_list(args):
    sys.path.insert(0, str(Path.cwd()))
    from dotenv import load_dotenv
    load_dotenv()
    from registry.registry import get_all_servers
    servers = get_all_servers()
    if not servers:
        print("No servers registered.")
        return
    print(f"\n{'NAME':<20} {'URL':<35} {'TOOLS'}")
    print("-" * 80)
    for s in servers:
        print(f"{s.name:<20} {s.url:<35} {', '.join(s.tools[:3])}{'...' if len(s.tools)>3 else ''}")
    print()


def cmd_add(args):
    sys.path.insert(0, str(Path.cwd()))
    from dotenv import load_dotenv
    load_dotenv()
    from registry.registry import add_server
    tools = [t.strip() for t in args.tools.split(",")]
    server = add_server(
        name=args.name,
        description=args.desc or "",
        url=args.url,
        transport=args.transport or "http",
        tools=tools,
    )
    print(f"✓ Added '{server.name}' to registry")


def cmd_remove(args):
    sys.path.insert(0, str(Path.cwd()))
    from dotenv import load_dotenv
    load_dotenv()
    from registry.registry import remove_server
    ok = remove_server(args.name)
    print(f"✓ Removed '{args.name}'" if ok else f"✗ '{args.name}' not found")


def main():
    parser = argparse.ArgumentParser(
        prog="mcp-gateway",
        description="MCP Gateway — Control Your MCP",
    )
    sub = parser.add_subparsers(dest="command", metavar="command")

    # init
    sub.add_parser("init", help="Create .env in current folder")

    # start
    start_p = sub.add_parser("start", help="Start the gateway")
    start_p.add_argument("--port", type=int, default=8000, help="Port (default: 8000)")
    start_p.add_argument("--reload", action="store_true", help="Auto-reload on file changes")

    # list
    sub.add_parser("list", help="List registered servers")

    # add
    add_p = sub.add_parser("add", help="Add a server to registry")
    add_p.add_argument("--name", required=True)
    add_p.add_argument("--url", required=True)
    add_p.add_argument("--tools", required=True, help="Comma-separated tool names")
    add_p.add_argument("--desc", default="")
    add_p.add_argument("--transport", default="http")

    # remove
    rem_p = sub.add_parser("remove", help="Remove a server from registry")
    rem_p.add_argument("--name", required=True)

    args = parser.parse_args()

    if args.command == "init":
        cmd_init(args)
    elif args.command == "start":
        cmd_start(args)
    elif args.command == "list":
        cmd_list(args)
    elif args.command == "add":
        cmd_add(args)
    elif args.command == "remove":
        cmd_remove(args)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
